[build]
target = "msp430-none-elf"

[unstable]
build-std = ["core"]

[target.msp430-none-elf]
linker = "/Users/davidfalkner/ti/msp430-gcc-9.3.1.11_macos/bin/msp430-elf-gcc"
rustflags = ["-C", "link-arg=-mmcu=msp430fr5969", "-C", "link-arg=-nostartfiles", "-C", "link-arg=-T", "-C", "link-arg=memory.x"]
runner = "/Applications/ti/ccs2051/ccs/ccs_base/DebugServer/bin/DSLite load -c MSP430FR5969.ccxml -f"
